version: '3.9'

services:
  rednode:
    container_name: rednode
    image: nodered/node-red:latest
    volumes:
      - node_red_data:/data
    ports:
      - 1880:1880
    restart: unless-stopped

volumes:
  node_red_data: